# Generated by Django 5.0.3 on 2024-04-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0008_product_slug_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug_name', models.SlugField()),
                ('products', models.ManyToManyField(blank=True, to='products_app.product')),
            ],
        ),
    ]
