# Generated by Django 5.0.3 on 2024-04-18 00:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_usersessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSessions',
            new_name='UserSession',
        ),
    ]
