# Generated by Django 5.0.3 on 2024-04-12 17:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_active_order_billing_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('order_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
