# Generated by Django 5.0.3 on 2024-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpref',
            name='mailchimp_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
