# Generated by Django 5.0.3 on 2024-04-02 20:07

import products_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products_app.models.upload_image_path),
        ),
    ]
