# Generated by Django 5.0.3 on 2024-04-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
