# Generated by Django 5.0.3 on 2024-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_name',
            field=models.SlugField(default='', max_length=120),
        ),
    ]
