# Generated by Django 5.0.3 on 2024-05-16 16:38

import products_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0011_alter_productfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to=products_app.models.upload_product_file_loc),
        ),
    ]
