# Generated by Django 5.0.3 on 2024-04-20 01:32

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_card_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=120)),
                ('paid', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_message', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.billingprofile')),
            ],
            managers=[
                ('charge_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
